# Mihomo / Clash Meta proxy config
# Generated by render-client-info.sh
# DO NOT commit actual values to public repo

proxies:
  - name: "DMIT-HY2"
    type: hysteria2
    server: ${HY2_DOMAIN}
    port: ${HY2_PORT}
    password: ${HY2_AUTH_PASSWORD}
    obfs: salamander
    obfs-password: ${HY2_OBFS_PASSWORD}
    sni: ${HY2_DOMAIN}
    skip-cert-verify: ${HY2_INSECURE_BOOL}
