# Official Hysteria 2 client config
# Generated by render-client-info.sh
# DO NOT commit actual values to public repo

server: ${HY2_DOMAIN}:${HY2_PORT}

auth: ${HY2_USER}:${HY2_AUTH_PASSWORD}

obfs:
  type: salamander
  salamander:
    password: ${HY2_OBFS_PASSWORD}

tls:
  sni: ${HY2_DOMAIN}
  insecure: ${HY2_INSECURE}

bandwidth:
  up: 20 mbps
  down: 100 mbps

socks5:
  listen: 127.0.0.1:7898

http:
  listen: 127.0.0.1:7899
