# Hysteria 2 server config — Self-signed cert mode
# Generated by render-server-config.sh
# DO NOT commit actual values to public repo
#
# WARNING: Self-signed certs require insecure=1 on clients.
# Switch to real cert (Let's Encrypt / acme.sh) for production.

listen: :${HY2_PORT}

tls:
  cert: /etc/hysteria/certs/${HY2_DOMAIN}.crt
  key: /etc/hysteria/certs/${HY2_DOMAIN}.key
  sniGuard: dns-san

auth:
  type: userpass
  userpass:
    ${HY2_USER}: ${HY2_AUTH_PASSWORD}

obfs:
  type: salamander
  salamander:
    password: ${HY2_OBFS_PASSWORD}

bandwidth:
  up: ${HY2_BANDWIDTH_UP}
  down: ${HY2_BANDWIDTH_DOWN}

trafficStats:
  listen: 127.0.0.1:9999
  secret: ${HY2_TRAFFIC_SECRET}

masquerade:
  type: proxy
  proxy:
    url: ${HY2_MASQUERADE_URL}
    rewriteHost: true
